#!/bin/sh

# https://github.com/RMerl/asuswrt-merlin/wiki/Using-ipset
# Peer Guardian V2

# Loading ipset modules
lsmod | grep "ip_set_iptreemap" > /dev/null 2>&1 || \
for module in ip_set ip_set_iptreemap ipt_set; do
    insmod $module
done

# Create the BluetackLevel1 (primary) if does not exists
if [ "$(ipset --swap BluetackLevel1 BluetackLevel1 2>&1 | grep 'Unknown set')" != "" ]; then
  ipset --create BluetackLevel1 iptreemap
fi

# [ -z "$(iptables-save | grep BluetackLevel1)" ] && iptables -I FORWARD -m set --match-set BluetackLevel1 src,dst -j DROP

# -s, --source address[/mask][,...]
# -d, --destination address[/mask][,...]
#[ -z "$(iptables-save | grep BluetackLevel1)" ] && iptables -I FORWARD -s 192.168.1.60 -m set --match-set BluetackLevel1 dst -j DROP
#[ -z "$(iptables-save | grep BluetackLevel1)" ] && iptables -I FORWARD -d 192.168.1.60 -m set --match-set BluetackLevel1 src -j DROP
[ -z "$(iptables-save | grep 'FORWARD -s 192.168.1.60/32 -m set --match-set BluetackLevel1 dst -j DROP')" ] && iptables -I FORWARD -s 192.168.1.60 -m set --match-set BluetackLevel1 dst -j DROP
[ -z "$(iptables-save | grep 'FORWARD -d 192.168.1.60/32 -m set --match-set BluetackLevel1 src -j DROP')" ] && iptables -I FORWARD -d 192.168.1.60 -m set --match-set BluetackLevel1 src -j DROP

# Destroy this transient set just in case
ipset --destroy BluetackLevel2 > /dev/null 2>&1

# Load the latest rule(s)

TODAY=`date +"%Y%m%d"`

(echo -e "-N BluetackLevel2 iptreemap\n" && \
 nice wget -q -O - "http://list.iblocklist.com/?list=bt_level1&fileformat=p2p&archiveformat=gz" | \
    nice gunzip | nice cut -d: -f2 | nice grep -E "^[-0-9.]+$" | \
    nice sed 's/^/-A BluetackLevel2 /' && \
 echo -e "\nCOMMIT\n" \
) | \
nice ipset --restore && \
nice ipset --swap BluetackLevel2 BluetackLevel1 && \
nice ipset --destroy BluetackLevel2
nice ipset --save BluetackLevel1 > /tmp/mnt/SanDisk_Cruzer/ipset_lists/BluetackLevel1.ipset.$TODAY.bak 2>&1
exit $?
